"""Renders an AnalyzeResponse as a shareable Markdown report.

Used by the ``/api/v1/analyze/{id}/export`` endpoint (and directly if you
just want a report from Python) so a DBA can paste findings into a ticket
or runbook without screenshotting the UI.
"""
from __future__ import annotations

from app.models import AnalyzeResponse


def to_markdown(result: AnalyzeResponse) -> str:
    lines: list[str] = []
    lines.append(f"# pgPlanAdvisor report — {result.id}")
    lines.append("")
    lines.append(f"*Generated: {result.created_at.isoformat()}*")
    if result.label:
        lines.append(f"*Label: {result.label}*")
    lines.append("")
    if result.query:
        lines.append("## Query")
        lines.append("")
        lines.append("```sql")
        lines.append(result.query.strip())
        lines.append("```")
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(result.summary)
    lines.append("")
    lines.append(f"- Execution time: **{result.total_runtime_ms:.2f} ms**")
    lines.append(f"- Planning time: **{result.planning_time_ms:.2f} ms**")
    lines.append(f"- Findings: **{len(result.top_findings)}**")
    lines.append("")

    if result.top_findings:
        lines.append("## Findings")
        lines.append("")
        for f in result.top_findings:
            lines.append(f"### [{f.severity.value.upper()}] {f.title}")
            lines.append("")
            lines.append(f"*Category: {f.category} · Node: `{f.node_path}` · Rule: `{f.rule_id}`*")
            lines.append("")
            lines.append("**Evidence**")
            lines.append("")
            for e in f.evidence:
                lines.append(f"- {e}")
            lines.append("")
            lines.append(f"**Recommendation:** {f.recommendation}")
            lines.append("")
            if f.checks:
                lines.append("**What to check**")
                lines.append("")
                for c in f.checks:
                    lines.append(f"- {c}")
                lines.append("")

    lines.append("## DBA Checklist")
    lines.append("")
    for c in result.investigation_checklist:
        lines.append(f"- [ ] {c}")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by [pgPlanAdvisor](https://github.com/nam255199/pgPlanAdvisor).*")
    return "\n".join(lines)
